"""
Vector Operations Explorer

Features:
- dot product
- cross product (only for 3D; if inputs are 2D, cross returns scalar z-component)
- magnitude
- angle between vectors (radians and degrees)
- optional visual representation (2D or 3D) using matplotlib

Usage examples:
$ python vector_operations_explorer.py --v1 "1,2,3" --v2 "4,5,6" --plot 3d
$ python vector_operations_explorer.py --v1 "3,4" --v2 "-1,2" --plot 2d --deg

Dependencies: numpy, matplotlib
Install: pip install numpy matplotlib

Author: Generated by ChatGPT — you can ask me to convert this to a Jupyter notebook or a small web app.
"""

import argparse
import numpy as np
import math
import sys

try:
    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d import Axes3D  # noqa: F401 (import for 3D projection)
except Exception:
    plt = None


def parse_vector(s):
    """Parse a vector string like "1,2,3" into a numpy array."""
    parts = [p.strip() for p in s.split(",") if p.strip() != ""]
    if len(parts) == 0:
        raise ValueError("Empty vector")
    return np.array([float(x) for x in parts], dtype=float)


def magnitude(v):
    return np.linalg.norm(v)


def dot_product(a, b):
    return float(np.dot(a, b))


def cross_product(a, b):
    # If both are 3D, return full 3D cross. If 2D, return scalar z (same as treating them as 3D with z=0)
    if a.size == 3 and b.size == 3:
        return np.cross(a, b)
    elif a.size == 2 and b.size == 2:
        # return scalar z-component
        return float(a[0] * b[1] - a[1] * b[0])
    else:
        # try to upcast to 3D by padding zeros
        a3 = np.zeros(3)
        b3 = np.zeros(3)
        a3[: min(3, a.size)] = a[: min(3, a.size)]
        b3[: min(3, b.size)] = b[: min(3, b.size)]
        return np.cross(a3, b3)


def angle_between(a, b, degrees=False):
    denom = magnitude(a) * magnitude(b)
    if denom == 0:
        raise ValueError("Angle undefined for zero-length vector")
    cos_theta = dot_product(a, b) / denom
    # numeric safety
    cos_theta = max(min(cos_theta, 1.0), -1.0)
    theta = math.acos(cos_theta)
    return math.degrees(theta) if degrees else theta


def print_summary(a, b, show_degrees=False):
    print("Vector A:", a)
    print("Vector B:", b)
    print("Magnitude A: {:.6f}".format(magnitude(a)))
    print("Magnitude B: {:.6f}".format(magnitude(b)))
    print("Dot product: {:.6f}".format(dot_product(a, b)))
    cp = cross_product(a, b)
    print("Cross product:", cp)
    try:
        ang = angle_between(a, b, degrees=show_degrees)
        unit = "degrees" if show_degrees else "radians"
        print(f"Angle between (in {unit}): {ang:.6f}")
    except ValueError as e:
        print("Angle between: ", e)


def plot_vectors(a, b, kind="2d"):
    if plt is None:
        raise RuntimeError("matplotlib is required for plotting. Install it with `pip install matplotlib`")

    if kind == "2d":
        if a.size != 2 or b.size != 2:
            # try to use first two components
            a2 = a[:2]
            b2 = b[:2]
            print("Note: vectors not 2D. Using first two components for plotting.")
        else:
            a2 = a
            b2 = b

        fig, ax = plt.subplots()
        ax.axhline(0, linewidth=0.5)
        ax.axvline(0, linewidth=0.5)
        ax.quiver(0, 0, a2[0], a2[1], angles="xy", scale_units="xy", scale=1, label="A")
        ax.quiver(0, 0, b2[0], b2[1], angles="xy", scale_units="xy", scale=1, label="B")
        # set limits
        allx = [0, a2[0], b2[0]]
        ally = [0, a2[1], b2[1]]
        margin = 0.5
        xmin, xmax = min(allx) - margin, max(allx) + margin
        ymin, ymax = min(ally) - margin, max(ally) + margin
        ax.set_xlim(xmin, xmax)
        ax.set_ylim(ymin, ymax)
        ax.set_aspect("equal", adjustable="box")
        ax.legend()
        ax.set_title("2D Vector Plot")
        plt.grid(True)
        plt.show()

    elif kind == "3d":
        # upcast to 3D
        a3 = np.zeros(3)
        b3 = np.zeros(3)
        a3[: min(3, a.size)] = a[: min(3, a.size)]
        b3[: min(3, b.size)] = b[: min(3, b.size)]

        fig = plt.figure()
        ax = fig.add_subplot(111, projection="3d")
        ax.quiver(0, 0, 0, a3[0], a3[1], a3[2], length=1.0, normalize=False)
        ax.quiver(0, 0, 0, b3[0], b3[1], b3[2], length=1.0, normalize=False)

        allx = [0, a3[0], b3[0]]
        ally = [0, a3[1], b3[1]]
        allz = [0, a3[2], b3[2]]
        margin = max(0.5, max(map(abs, allx + ally + allz)) * 0.2)
        ax.set_xlim(min(allx) - margin, max(allx) + margin)
        ax.set_ylim(min(ally) - margin, max(ally) + margin)
        ax.set_zlim(min(allz) - margin, max(allz) + margin)
        ax.set_xlabel("X")
        ax.set_ylabel("Y")
        ax.set_zlabel("Z")
        ax.set_title("3D Vector Plot")
        plt.show()

    else:
        raise ValueError("Unknown plot kind: choose '2d' or '3d'")


def main(argv=None):
    parser = argparse.ArgumentParser(description="Vector Operations Explorer")
    parser.add_argument("--v1", required=True, help='Vector 1 as comma-separated numbers, e.g. "1,2,3"')
    parser.add_argument("--v2", required=True, help='Vector 2 as comma-separated numbers, e.g. "4,5,6"')
    parser.add_argument("--plot", choices=["2d", "3d", "none"], default="none", help="Show a plot: 2d or 3d")
    parser.add_argument("--deg", action="store_true", help="Show angle in degrees (default: radians)")
    parser.add_argument("--silent", action="store_true", help="Only output JSON summary")

    args = parser.parse_args(argv)

    try:
        a = parse_vector(args.v1)
        b = parse_vector(args.v2)
    except Exception as e:
        print("Error parsing vectors:", e)
        sys.exit(1)

    if args.silent:
        # minimal JSON-like output
        out = {
            "v1": a.tolist(),
            "v2": b.tolist(),
            "magnitude_v1": magnitude(a),
            "magnitude_v2": magnitude(b),
            "dot": dot_product(a, b),
            "cross": (cross_product(a, b).tolist() if hasattr(cross_product(a, b), "tolist") else cross_product(a, b)),
            "angle": angle_between(a, b, degrees=args.deg),
            "angle_in_degrees": args.deg,
        }
        import json

        print(json.dumps(out, indent=2))
        return

    print_summary(a, b, show_degrees=args.deg)

    if args.plot != "none":
        try:
            plot_vectors(a, b, kind=args.plot)
        except Exception as e:
            print("Plot failed:", e)


if __name__ == "__main__":
    main()
